import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

export type Currency = "NGN" | "USD" | "EUR" | "INR" | "GHS";
export type Language = "en" | "ha" | "ig" | "yo";

interface CurrencyInfo {
  code: Currency;
  symbol: string;
  name: string;
}

interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
}

export const currencies: CurrencyInfo[] = [
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi" },
];

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
];

interface SettingsContextType {
  currency: Currency;
  setCurrency: (currency: Currency) => void;
  language: Language;
  setLanguage: (language: Language) => void;
  formatCurrency: (amount: number) => string;
  t: (key: string) => string;
  getCurrencyInfo: () => CurrencyInfo;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.inventory": "Inventory",
    "nav.sales": "Record Sale",
    "nav.reports": "Reports",
    "nav.reconciliation": "Reconciliation",
    "nav.audit": "Audit Log",
    "nav.team": "Team",
    "nav.profile": "Profile",
    "nav.install": "Install App",
    "nav.signout": "Sign Out",
    "nav.navigation": "Navigation",
    // Common
    "common.save": "Save Changes",
    "common.saving": "Saving...",
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.secondsAgo": "seconds ago",
    "common.minuteAgo": "minute ago",
    "common.minutesAgo": "minutes ago",
    "common.hourAgo": "hour ago",
    "common.hoursAgo": "hours ago",
    "common.dayAgo": "day ago",
    "common.daysAgo": "days ago",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.actions": "Actions",
    "common.system": "System",
    "common.unknownProduct": "Unknown Product",
    "common.copied": "Copied to clipboard!",
    "common.staff": "Staff",
    "common.fillFields": "Please fill in all fields",
    "common.unknown": "Unknown",
    // Profile
    "profile.title": "Profile Settings",
    "profile.subtitle": "Manage your account information",
    "profile.personal": "Personal Information",
    "profile.name": "Full Name",
    "profile.email": "Email",
    "profile.phone": "Phone Number",
    "profile.password": "Change Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.updatePassword": "Update Password",
    "profile.preferences": "Preferences",
    "profile.currency": "Currency",
    "profile.language": "Language",
    "profile.selectCurrency": "Select currency",
    "profile.selectLanguage": "Select language",
    "profile.namePlaceholder": "Enter your full name",
    "profile.emailPlaceholder": "Enter your email",
    "profile.phonePlaceholder": "Enter your phone number",
    "profile.passwordPlaceholder": "Enter new password (min 6 characters)",
    "profile.confirmPasswordPlaceholder": "Confirm new password",
    "profile.loadFailed": "Failed to load profile",
    "profile.updated": "Profile updated successfully!",
    "profile.passwordsNoMatch": "Passwords don't match",
    "profile.passwordTooShort": "Password must be at least 6 characters",
    "profile.passwordUpdated": "Password updated successfully!",
    "profile.passwordUpdateFailed": "Failed to update password",
    // Index / Landing
    "index.welcome": "Welcome to",
    "index.subtitle": "The complete inventory and sales tracking solution designed specifically for small shop owners. Simple, powerful, and works offline.",
    "index.getStarted": "Get Started",
    "index.featuresTitle": "Everything you need to manage your shop",
    "index.featuresSubtitle": "Built for simplicity, designed for growth",
    "index.feature1Title": "Real-time Sales Tracking",
    "index.feature1Desc": "Monitor your sales as they happen with live updates and instant notifications",
    "index.feature2Title": "Smart Inventory Management",
    "index.feature2Desc": "Keep track of stock levels with automatic low-stock alerts",
    "index.feature3Title": "Secure & Reliable",
    "index.feature3Desc": "Your data is protected with enterprise-grade security and daily backups",
    "index.feature4Title": "Works Offline",
    "index.feature4Desc": "Record sales even without internet. Syncs automatically when back online",
    "index.ctaTitle": "Ready to transform your business?",
    "index.ctaSubtitle": "Join hundreds of shop owners who trust ShopCount to manage their inventory and sales",
    "index.startTrial": "Start Your Free Trial",
    // Install
    "install.title": "Install ShopCount",
    "install.subtitle": "Get the mobile app experience",
    "install.installedTitle": "App Installed!",
    "install.installedDesc": "ShopCount is now installed on your device. You can access it from your home screen.",
    "install.whyTitle": "Why Install ShopCount?",
    "install.feature1": "Works offline - Record sales even without internet",
    "install.feature2": "Quick access from home screen",
    "install.feature3": "Fast loading and smooth performance",
    "install.feature4": "Full-screen app experience",
    "install.button": "Install App",
    "install.howTitle": "To install ShopCount on your device:",
    "install.howIos": "Tap the Share button, then \"Add to Home Screen\"",
    "install.howAndroid": "Tap the menu (⋮), then \"Add to Home Screen\" or \"Install App\"",
    "install.offlineTitle": "Features Available Offline:",
    "install.offline1": "Record sales transactions",
    "install.offline2": "View product inventory",
    "install.offline3": "Check low stock alerts",
    "install.offline4": "Access recent activity",
    "install.syncNote": "All offline actions will automatically sync when you're back online.",
    // Auth
    "auth.tagline": "Inventory & Sales Tracking for Small Businesses",
    "auth.loginTab": "Login",
    "auth.signupTab": "Sign Up",
    "auth.resetPasswordTitle": "Reset Password",
    "auth.emailLabel": "Email",
    "auth.emailPlaceholder": "Enter your email",
    "auth.passwordLabel": "Password",
    "auth.passwordPlaceholder": "Enter your password",
    "auth.forgotPassword": "Forgot password?",
    "auth.loginButton": "Login",
    "auth.loggingIn": "Logging in...",
    "auth.loginSuccess": "Login successful!",
    "auth.signupNameLabel": "Full Name",
    "auth.signupNamePlaceholder": "Enter your full name",
    "auth.signupPhoneLabel": "Phone Number (Optional)",
    "auth.signupPhonePlaceholder": "Enter your phone number",
    "auth.signupPasswordLabel": "Password",
    "auth.signupPasswordPlaceholder": "Create a password (min 6 characters)",
    "auth.signupButton": "Create Account",
    "auth.signingUp": "Creating account...",
    "auth.signupSuccess": "Account created successfully!",
    "auth.resetLinkButton": "Send Reset Link",
    "auth.sending": "Sending...",
    "auth.resetLinkSent": "Password reset email sent! Check your inbox.",
    "auth.backToLogin": "Back to Login",
    "auth.termsNote": "By continuing, you agree to our Terms of Service and Privacy Policy",
    // NotFound
    "notfound.title": "404",
    "notfound.subtitle": "Oops! Page not found",
    "notfound.returnHome": "Return to Home",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Welcome back! Here is your business overview",
    "dashboard.todaySales": "Today's Sales",
    "dashboard.totalStock": "Total Stock",
    "dashboard.lowStock": "Low Stock Items",
    "dashboard.totalProfit": "Total Profit",
    "dashboard.productsSold": "products sold",
    "dashboard.totalInventory": "Total inventory value",
    "dashboard.needAttention": "need attention",
    "dashboard.allGood": "All stock levels healthy",
    "dashboard.units": "Units",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.noActivity": "No recent activity",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.stockAdded": "Stock added",
    "dashboard.saleRecorded": "Sale recorded",
    "dashboard.stockAdjusted": "Stock adjusted",
    "dashboard.viewAll": "View All",
    // Inventory
    "inventory.title": "Inventory Management",
    "inventory.subtitle": "Manage your products and stock levels",
    "inventory.addProduct": "Add Product",
    "inventory.editProduct": "Edit Product",
    "inventory.updateProduct": "Update Product",
    "inventory.productName": "Product Name",
    "inventory.category": "Category",
    "inventory.categoryOptional": "Category (Optional)",
    "inventory.costPrice": "Cost Price",
    "inventory.sellingPrice": "Selling Price",
    "inventory.stock": "Current Stock",
    "inventory.initialStock": "Initial Stock",
    "inventory.threshold": "Low Stock Alert",
    "inventory.searchPlaceholder": "Search products...",
    "inventory.allCategories": "All Categories",
    "inventory.noProducts": "No products yet",
    "inventory.noProductsHint": "Get started by adding your first product to the inventory",
    "inventory.addProductFirst": "Add Your First Product",
    "inventory.noProductsFound": "No products found",
    "inventory.adjustSearch": "Try adjusting your search or filter criteria",
    "inventory.inStock": "in stock",
    "inventory.profitUnit": "Profit/Unit",
    "inventory.addStock": "Add Stock",
    "inventory.stockQty": "Quantity to Add",
    "inventory.enterQty": "Enter quantity",
    "inventory.currentStockHint": "Current stock: {count} units",
    "inventory.deleteConfirm": "Delete Product?",
    "inventory.deleteDescription": "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    "inventory.manageInventory": "Manage Inventory",
    "inventory.stockLabel": "Stock",
    // Sales
    "sales.title": "Record Sale",
    "sales.subtitle": "Quick and easy sales recording",
    "sales.selectProduct": "Select Product",
    "sales.selectProductPlaceholder": "Search for a product...",
    "sales.unitPrice": "Unit Price",
    "sales.profitPerUnit": "Profit/Unit",
    "sales.availableStock": "Available Stock",
    "sales.quantity": "Quantity",
    "sales.quantityPlaceholder": "Enter quantity",
    "sales.totalAmount": "Total Amount",
    "sales.totalProfitLabel": "Total Profit",
    "sales.recording": "Recording...",
    "sales.recordSale": "Record Sale",
    "sales.downloadReceipt": "Download Receipt",
    "sales.recordedAndSynced": "Sale recorded and synced!",
    "sales.savedOffline": "Sale saved offline (will sync later)",
    "sales.loadFailed": "Failed to load products",
    "sales.enterValidQuantity": "Please select a product and enter a valid quantity",
    "sales.insufficientStock": "Insufficient stock available",
    "sales.failed": "Failed to record sale",
    "sales.receiptDownloaded": "Receipt downloaded!",
    "sales.allSynced": "All data synced",
    "sales.pendingSyncs": "{count} sales pending sync",
    // Reports
    "reports.title": "Reports & Analytics",
    "reports.subtitle": "Track your sales performance",
    "reports.daily": "Daily",
    "reports.weekly": "Weekly",
    "reports.monthly": "Monthly",
    "reports.revenue": "Revenue",
    "reports.profit": "Profit",
    "reports.avgSaleValue": "Avg Sale Value",
    "reports.salesTrend": "Sales Trend",
    "reports.topProducts": "Top Selling Products",
    "reports.noData": "No sales data available",
    "reports.unitsSold": "units sold",
    "reports.loading": "Loading reports...",
    "reports.failed": "Failed to load reports",
    // Reconciliation
    "reconciliation.title": "Cash Reconciliation",
    "reconciliation.subtitle": "Compare expected vs received cash",
    "reconciliation.new": "New Reconciliation",
    "reconciliation.date": "Date",
    "reconciliation.expected": "Expected Cash",
    "reconciliation.expectedHint": "Based on sales for",
    "reconciliation.received": "Cash Received",
    "reconciliation.receivedPlaceholder": "Enter actual cash received",
    "reconciliation.discrepancyDetected": "Discrepancy Detected",
    "reconciliation.perfectMatch": "Perfect Match!",
    "reconciliation.short": "Short",
    "reconciliation.over": "Over",
    "reconciliation.notes": "Notes",
    "reconciliation.notesPlaceholder": "Add any notes about this reconciliation...",
    "reconciliation.submit": "Submit Reconciliation",
    "reconciliation.history": "Recent Records",
    "reconciliation.noRecords": "No records yet",
    "reconciliation.approved": "Approved",
    "reconciliation.disputed": "Disputed",
    "reconciliation.saving": "Saving reconciliation...",
    "reconciliation.saved": "Reconciliation record saved!",
    "reconciliation.failed": "Failed to save reconciliation",
    "reconciliation.loadFailed": "Failed to load reconciliation records",
    "reconciliation.enterAmount": "Please enter the cash received amount",
    "reconciliation.expectedLabel": "Expected",
    "reconciliation.receivedLabel": "Received",
    "reconciliation.statusApproved": "Approved",
    "reconciliation.statusDisputed": "Disputed",
    "reconciliation.isPartial": "This is a partial count (keep remaining sales for later)",
    // Audit Log
    "audit.title": "Audit Log",
    "audit.subtitle": "Track all inventory changes",
    "audit.action": "Action",
    "audit.product": "Product",
    "audit.quantity": "Quantity Change",
    "audit.date": "Date",
    "audit.noLogs": "No audit logs found",
    "audit.loadFailed": "Failed to load audit logs",
    "audit.previousStock": "Previous Stock",
    "audit.newStock": "New Stock",
    "audit.actionSale": "Sale",
    "audit.actionRestock": "Restock",
    "audit.actionAdjustment": "Adjustment",
    // Team
    "team.title": "Team Management",
    "team.subtitle": "Manage your sales representatives",
    "team.addRep": "Add Sales Rep",
    "team.createAccount": "Create Account",
    "team.noReps": "No sales reps yet",
    "team.noRepsHint": "Add your first sales rep to get started",
    "team.dateAdded": "Date Added",
    "team.repAdded": "Sales rep added successfully!",
    "team.repRemoved": "Sales rep removed",
    "team.passwordNote": "A password will be automatically generated. You will see the credentials after creation.",
    "team.credentialsTitle": "Sales Rep Credentials",
    "team.credentialsWarning": "Save these credentials now! The password cannot be retrieved later.",
    "team.done": "Done",
    "team.addFailed": "Failed to add sales rep",
    "team.removeConfirm": "Remove {name} from your team?",
    "team.removeFailed": "Failed to remove team member",
    "team.loadFailed": "Failed to load team members",
    "team.fillFields": "Please fill in all fields",
    // Feedback
    "feedback.button": "Feedback",
  },
  ha: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.inventory": "Kayan Ajiya",
    "nav.sales": "Rubuta Sayarwa",
    "nav.reports": "Rahotanni",
    "nav.reconciliation": "Sulhu",
    "nav.audit": "Tarihin Aiki",
    "nav.team": "Ƙungiya",
    "nav.profile": "Bayanai",
    "nav.install": "Shigar da App",
    "nav.signout": "Fita",
    "nav.navigation": "Kewayawa",
    // Common
    "common.save": "Ajiye Canje-canje",
    "common.saving": "Ana Ajiyewa...",
    "common.loading": "Ana lodi...",
    "common.back": "Baya",
    "common.secondsAgo": "daƙiƙa da suka wuce",
    "common.minuteAgo": "minti daya da ya wuce",
    "common.minutesAgo": "minti da suka wuce",
    "common.hourAgo": "awa daya da ya wuce",
    "common.hoursAgo": "awa da suka wuce",
    "common.dayAgo": "kwana daya da ya wuce",
    "common.daysAgo": "kwana da suka wuce",
    "common.search": "Nema",
    "common.filter": "Tace",
    "common.add": "Ƙara",
    "common.edit": "Gyara",
    "common.delete": "Share",
    "common.cancel": "Soke",
    "common.confirm": "Tabbatar",
    "common.actions": "Ayyuka",
    "common.system": "Tsarin",
    "common.unknownProduct": "Kayan da ba a sani ba",
    "common.copied": "An kwafi!",
    "common.staff": "Ma'aikata",
    "common.unknown": "Ba a sani ba",
    // Profile
    "profile.title": "Saitunan Bayanai",
    "profile.subtitle": "Sarrafa bayanan asusunka",
    "profile.personal": "Bayanan Kai",
    "profile.name": "Cikakken Suna",
    "profile.email": "Imel",
    "profile.phone": "Lambar Waya",
    "profile.password": "Canza Kalmar Sirri",
    "profile.newPassword": "Sabuwar Kalmar Sirri",
    "profile.confirmPassword": "Tabbatar da Sabuwar Kalmar Sirri",
    "profile.updatePassword": "Sabunta Kalmar Sirri",
    "profile.preferences": "Zaɓuɓɓuka",
    "profile.currency": "Kuɗi",
    "profile.language": "Harshe",
    "profile.selectCurrency": "Zaɓi kuɗi",
    "profile.selectLanguage": "Zaɓi harshe",
    "profile.namePlaceholder": "Shigar da cikakken sunanka",
    "profile.emailPlaceholder": "Shigar da imel ɗinka",
    "profile.phonePlaceholder": "Shigar da lambar wayarka",
    "profile.passwordPlaceholder": "Shigar da sabuwar kalmar sirri (aƙalla haruffa 6)",
    "profile.confirmPasswordPlaceholder": "Tabbatar da sabuwar kalmar sirri",
    "profile.loadFailed": "An kasa loda bayanai",
    "profile.updated": "An sabunta bayanai cikin rárá!",
    "profile.passwordsNoMatch": "Kalmomin sirri ba su yi daidai ba",
    "profile.passwordTooShort": "Dole ne kalmar sirri ta kasance aƙalla haruffa 6",
    "profile.passwordUpdated": "An sabunta kalmar sirri yadda ya kamata!",
    "profile.passwordUpdateFailed": "An kasa sabunta kalmar sirri",
    // Index / Landing
    "index.welcome": "Barka da zuwa",
    "index.subtitle": "Cikakken maganin bin diddigin kaya da siyarwa da aka kera musamman don masu ƙananan shaguna. Mai sauƙi, mai ƙarfi, kuma yana aiki ba tare da intanet ba.",
    "index.getStarted": "Fara Yanzu",
    "index.featuresTitle": "Duk abin da kuke buƙata don sarrafa shagonku",
    "index.featuresSubtitle": "An gina shi don sauƙi, an tsara shi don girma",
    "index.feature1Title": "Bin Dididdigin Siyarwa Nan Take",
    "index.feature1Desc": "Kula da siyarwar ku yayin da suke faruwa tare da sabuntawa kai tsaye",
    "index.feature2Title": "Sarrafa Kayayyaki Cikin Wayo",
    "index.feature2Desc": "Kasance tare da matakan kaya tare da gargaɗin raguwar kaya ta atomatik",
    "index.feature3Title": "Amintacce & Abin Dogaro",
    "index.feature3Desc": "Ana kiyaye bayanan ku tare da tsaro mai daraja da adana bayanai yau da kullun",
    "index.feature4Title": "Yana Aiki Ba Tare da Intanet Ba",
    "index.feature4Desc": "Rubuta siyarwa koda babu intanet. Yana daidaitawa ta atomatik lokacin da intanet ta dawo",
    "index.ctaTitle": "Shin kun shirya don canza kasuwancin ku?",
    "index.ctaSubtitle": "Kasance tare da daruruwan masu shaguna waɗanda suka dogara ga ShopCount don sarrafa kayansu da siyarwa",
    "index.startTrial": "Fara Gwajin Kyauta",
    // Install
    "install.title": "Shigar da ShopCount",
    "install.subtitle": "Samun kwarewar aikace-aikacen tafi-da-gidanka",
    "install.installedTitle": "An shigar da App!",
    "install.installedDesc": "An shigar da ShopCount yanzu akan na'urarka. Kuna iya samun dama gare shi daga shafin farko.",
    "install.whyTitle": "Me Yasa Za a Shigar da ShopCount?",
    "install.feature1": "Yana aiki ba tare da intanet ba - Rubuta siyarwa koda babu intanet",
    "install.feature2": "Samun dama cikin sauri daga shafin farko",
    "install.feature3": "Yana lodi cikin sauri da aiki mai kyau",
    "install.feature4": "Cikakken kwarewar aikace-aikacen allo",
    "install.button": "Shigar da App",
    "install.howTitle": "Don shigar da ShopCount akan na'urarka:",
    "install.howIos": "Taɓa maɓallin Share, sannan \"Add to Home Screen\"",
    "install.howAndroid": "Taɓa menu (⋮), sannan \"Add to Home Screen\" ko \"Install App\"",
    "install.offlineTitle": "Ayyukan da Akwai Lokacin da Babu Intanet:",
    "install.offline1": "Rubuta bayanan siyarwa",
    "install.offline2": "Duba kayan ajiya",
    "install.offline3": "Duba gargaɗin raguwar kaya",
    "install.offline4": "Duba ayyukan kwanan nan",
    "install.syncNote": "Dukkan ayyukan da aka yi lokacin da babu intanet za su daidaita ta atomatik lokacin da intanet ta dawo.",
    // Auth
    "auth.tagline": "Bin diddikin Kaya & Siyarwa ga Ƙananan Kasuwanci",
    "auth.loginTab": "Shiga",
    "auth.signupTab": "Yi Rajista",
    "auth.resetPasswordTitle": "Sake Saita Kalmar Sirri",
    "auth.emailLabel": "Imel",
    "auth.emailPlaceholder": "Shigar da imel ɗinka",
    "auth.passwordLabel": "Kalmar Sirri",
    "auth.passwordPlaceholder": "Shigar da kalmar sirri",
    "auth.forgotPassword": "Kun manta kalmar sirri?",
    "auth.loginButton": "Shiga",
    "auth.loggingIn": "Ana shiga...",
    "auth.loginSuccess": "An shiga cikin nasara!",
    "auth.signupNameLabel": "Cikakken Suna",
    "auth.signupNamePlaceholder": "Shigar da cikakken sunanka",
    "auth.signupPhoneLabel": "Lambar Waya (Na zaɓi)",
    "auth.signupPhonePlaceholder": "Shigar da lambar wayarka",
    "auth.signupPasswordLabel": "Kalmar Sirri",
    "auth.signupPasswordPlaceholder": "Ƙirƙiri kalmar sirri (aƙalla haruffa 6)",
    "auth.signupButton": "Ƙirƙiri Asusu",
    "auth.signingUp": "Ana ƙirƙirar asusu...",
    "auth.signupSuccess": "An buɗe asusu cikin nasara!",
    "auth.resetLinkButton": "Aika Hanyar Sake Saitawa",
    "auth.sending": "Ana aikawa...",
    "auth.resetLinkSent": "An aika imel ɗin sake saita kalmar sirri! Duba imel ɗinka.",
    "auth.backToLogin": "Koma Zuwa Shiga",
    "auth.termsNote": "Ta ci gaba, kun amince da Sharuddan Sabis ɗinmu da Manufofin Sirri",
    // NotFound
    "notfound.title": "404",
    "notfound.subtitle": "Haba! Ba a sami shafin ba",
    "notfound.returnHome": "Koma Shafin Farko",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Barka da dawowa! Ga bayanin kasuwancin ku",
    "dashboard.todaySales": "Sayarwar Yau",
    "dashboard.totalStock": "Jimlar Kaya",
    "dashboard.lowStock": "Kayan da suka ragu",
    "dashboard.totalProfit": "Jimlar Riba",
    "dashboard.productsSold": "kayayyaki da aka sayar",
    "dashboard.totalInventory": "Jimlar darajar kaya",
    "dashboard.needAttention": "suna bukatar kulawa",
    "dashboard.allGood": "Dukkan adadin kaya suna da kyau",
    "dashboard.units": "Raka'a",
    "dashboard.recentActivity": "Ayyukan Kwanan Nan",
    "dashboard.noActivity": "Babu ayyuka kwanan nan",
    "dashboard.quickActions": "Hanyoyi Saurin Aiki",
    "dashboard.stockAdded": "An ƙara kaya",
    "dashboard.saleRecorded": "An rubuta sayarwa",
    "dashboard.stockAdjusted": "An daidaita kaya",
    "dashboard.viewAll": "Duba Duka",
    // Inventory
    "inventory.title": "Gudanar da Kayan Ajiya",
    "inventory.subtitle": "Sarrafa kayanku da adadinsu",
    "inventory.addProduct": "Ƙara Kaya",
    "inventory.editProduct": "Gyara Kaya",
    "inventory.updateProduct": "Sabunta Kaya",
    "inventory.productName": "Sunan Kaya",
    "inventory.category": "Nau'i",
    "inventory.categoryOptional": "Nau'i (Na zaɓi)",
    "inventory.costPrice": "Farashin Siye",
    "inventory.sellingPrice": "Farashin Sayarwa",
    "inventory.stock": "Adadin Yanzu",
    "inventory.initialStock": "Kayan Farko",
    "inventory.threshold": "Gargaɗin Ragowar Kaya",
    "inventory.searchPlaceholder": "Nemi kaya...",
    "inventory.allCategories": "Duk Nau'o'i",
    "inventory.noProducts": "Babu kaya tukunna",
    "inventory.noProductsHint": "Fara ta hanyar ƙara kaya na farko",
    "inventory.addProductFirst": "Ƙara Kaya na Farko",
    "inventory.noProductsFound": "Ba a sami kaya ba",
    "inventory.adjustSearch": "Gwada canza abin da kuke nema",
    "inventory.inStock": "a hannu",
    "inventory.profitUnit": "Riba/Raka'a",
    "inventory.addStock": "Ƙara Adadi",
    "inventory.stockQty": "Adadin da za a ƙara",
    "inventory.enterQty": "Shigar da adadi",
    "inventory.currentStockHint": "Adadin yanzu: {count} raka'a",
    "inventory.deleteConfirm": "Share Kaya?",
    "inventory.deleteDescription": "Shin kun tabbata kuna son share \"{name}\"? Ba za a iya dawo da shi ba.",
    "inventory.manageInventory": "Sarrafa Kaya",
    "inventory.stockLabel": "Kaya",
    // Sales
    "sales.title": "Rubuta Sayarwa",
    "sales.subtitle": "Rubuta sayarwa cikin sauri da sauƙi",
    "sales.selectProduct": "Zaɓi Kaya",
    "sales.selectProductPlaceholder": "Nemi kaya...",
    "sales.unitPrice": "Farashin Raka'a",
    "sales.profitPerUnit": "Riba/Raka'a",
    "sales.availableStock": "Kayan da ke Akwai",
    "sales.quantity": "Adadi",
    "sales.quantityPlaceholder": "Shigar da adadi",
    "sales.totalAmount": "Jimlar Kuɗi",
    "sales.totalProfitLabel": "Jimlar Riba",
    "sales.recording": "Ana rubutawa...",
    "sales.recordSale": "Rubuta Sayarwa",
    "sales.downloadReceipt": "Sauke Takardar Sayarwa",
    "sales.recordedAndSynced": "An rubuta kuma an daidaita sayarwa!",
    "sales.savedOffline": "An ajiye a waya (za a daidaita daga baya)",
    "sales.loadFailed": "An kasa loda kayayyaki",
    "sales.enterValidQuantity": "Da fatan za a zaɓi kaya kuma a shigar da adadin da ya dace",
    "sales.insufficientStock": "Kayan da ke akwai ba su isa ba",
    "sales.failed": "An kasa rubuta sayarwa",
    "sales.receiptDownloaded": "An sauke takardar sayarwa!",
    "sales.allSynced": "An daidaita komai",
    "sales.pendingSyncs": "Siyarwa {count} na jiran daidaitawa",
    // Reports
    "reports.title": "Rahotanni & Nazari",
    "reports.subtitle": "Bi diddigin aikin sayarwarka",
    "reports.daily": "Kullum",
    "reports.weekly": "Mako-mako",
    "reports.monthly": "Wata-wata",
    "reports.revenue": "Kudaden Shiga",
    "reports.profit": "Riba",
    "reports.salesTrend": "Yanayin Sayarwa",
    "reports.topProducts": "Kayan da ake sayar da su",
    "reports.noData": "Babu bayanan sayarwa",
    "reports.unitsSold": "aka sayar",
    "reports.loading": "Ana lodi...",
    "reports.failed": "An kasa loda rahotanni",
    // Reconciliation
    "reconciliation.title": "Sulhun Kuɗi",
    "reconciliation.subtitle": "Kwatanta kuɗin da ake tsammani da abin da aka karɓa",
    "reconciliation.new": "Sabon Sulhu",
    "reconciliation.date": "Kwanan Wata",
    "reconciliation.expected": "Kuɗin da Ake Tsammani",
    "reconciliation.expectedHint": "Bisa sayarwa na",
    "reconciliation.received": "Kuɗin da Aka Karɓa",
    "reconciliation.receivedPlaceholder": "Shigar da kuɗin da aka karɓa",
    "reconciliation.discrepancyDetected": "An sami sabani",
    "reconciliation.perfectMatch": "Daidai!",
    "reconciliation.short": "Ya gaza",
    "reconciliation.over": "Ya wuce",
    "reconciliation.notes": "Bayanai",
    "reconciliation.notesPlaceholder": "Ƙara bayanai game da wannan sulhu...",
    "reconciliation.submit": "Aika Sulhu",
    "reconciliation.history": "Bayanan Kwanan Nan",
    "reconciliation.noRecords": "Babu bayanan tukuna",
    "reconciliation.approved": "An amince",
    "reconciliation.disputed": "An ƙi",
    "reconciliation.saving": "Ana ajiyar sulhu...",
    "reconciliation.saved": "An ajiye bayanan sulhu!",
    "reconciliation.failed": "An kasa ajiye sulhu",
    "reconciliation.loadFailed": "An kasa loda bayanan sulhu",
    "reconciliation.enterAmount": "Da fatan za a shigar da adadin kuɗin da aka karɓa",
    "reconciliation.expectedLabel": "Abin Tsammani",
    "reconciliation.receivedLabel": "Abin da aka Karɓa",
    "reconciliation.statusApproved": "An amince",
    "reconciliation.statusDisputed": "An ƙi",
    "reconciliation.isPartial": "Wannan lissafin sashe ne (ajiye sauran tallace-tallace na gaba)",
    // Audit Log
    "audit.title": "Tarihin Aiki",
    "audit.subtitle": "Bi diddigin duk canje-canjen kaya",
    "audit.action": "Aiki",
    "audit.product": "Kaya",
    "audit.quantity": "Canjin Adadi",
    "audit.date": "Kwanan Wata",
    "audit.noLogs": "Babu tarihin aiki",
    "audit.loadFailed": "An kasa loda tarihin aiki",
    "audit.previousStock": "Adadin Da",
    "audit.newStock": "Sabuwar Adadi",
    "audit.actionSale": "Sayarwa",
    "audit.actionRestock": "Ƙara Kaya",
    "audit.actionAdjustment": "Daidaitawa",
    // Team
    "team.title": "Gudanar da Ƙungiya",
    "team.subtitle": "Sarrafa masu sayarwar ka",
    "team.addRep": "Ƙara Mai Sayarwa",
    "team.createAccount": "Ƙirƙiri Asusu",
    "team.noReps": "Babu masu sayarwa tukuna",
    "team.noRepsHint": "Ƙara mai sayarwa na farko don fara",
    "team.dateAdded": "Ranar da aka ƙara",
    "team.repAdded": "An ƙara mai sayarwa!",
    "team.repRemoved": "An cire mai sayarwa",
    "team.passwordNote": "Za a samar da kalmar sirri ta atomatik. Za ka ga bayanan bayan ƙirƙira.",
    "team.credentialsTitle": "Bayanan Mai Sayarwa",
    "team.credentialsWarning": "Ajiye waɗannan bayanan yanzu! Ba za a iya dawo da kalmar sirri ba.",
    "team.done": "An gama",
    "team.addFailed": "An kasa ƙara mai sayarwa",
    "team.removeConfirm": "Cire {name} daga ƙungiyar ku?",
    "team.removeFailed": "An kasa cire memba na ƙungiyar",
    "team.loadFailed": "An kasa loda mambobin ƙungiyar",
    "team.fillFields": "Da fatan za a cika dukkan bayanan",
    // Feedback
    "feedback.button": "Ra'ayi",
  },
  ig: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.inventory": "Ngwa Ahịa",
    "nav.sales": "Dee Ahịa",
    "nav.reports": "Akụkọ",
    "nav.reconciliation": "Nhazi",
    "nav.audit": "Akwụkwọ Ọrụ",
    "nav.team": "Ndị Otu",
    "nav.profile": "Profaịlụ",
    "nav.install": "Wụnye App",
    "nav.signout": "Pụọ",
    "nav.navigation": "Ịgagharị",
    // Common
    "common.save": "Chekwaa Mgbanwe",
    "common.saving": "Na-echekwa...",
    "common.loading": "Na-ebutere...",
    "common.back": "Azụ",
    "common.secondsAgo": "sekọnd gara aga",
    "common.minuteAgo": "nkeji gara aga",
    "common.minutesAgo": "nkeji gara aga",
    "common.hourAgo": "awa gara aga",
    "common.hoursAgo": "awa gara aga",
    "common.dayAgo": "ụbọchị gara aga",
    "common.daysAgo": "ụbọchị gara aga",
    "common.search": "Chọọ",
    "common.filter": "Họrọ",
    "common.add": "Tinye",
    "common.edit": "Dezie",
    "common.delete": "Hichapụ",
    "common.cancel": "Kagbuo",
    "common.confirm": "Kwado",
    "common.actions": "Ọrụ",
    "common.system": "Sistemụ",
    "common.unknownProduct": "Ngwa a na-amaghị",
    "common.copied": "E depụtaghachiri ya!",
    "common.staff": "Ndị Ọrụ",
    "common.unknown": "Amaghị",
    // Profile
    "profile.title": "Ntọala Profaịlụ",
    "profile.subtitle": "Jikwaa ozi akaụntụ gị",
    "profile.personal": "Ozi Onwe",
    "profile.name": "Aha Zuru Oke",
    "profile.email": "Email",
    "profile.phone": "Nọmba Ekwentị",
    "profile.password": "Gbanwee Okwuntughe",
    "profile.newPassword": "Okwuntughe Ọhụrụ",
    "profile.confirmPassword": "Kwado Okwuntughe Ọhụrụ",
    "profile.updatePassword": "Melite Okwuntughe",
    "profile.preferences": "Nhọrọ",
    "profile.currency": "Ego",
    "profile.language": "Asụsụ",
    "profile.selectCurrency": "Họrọ ego",
    "profile.selectLanguage": "Họrọ asụsụ",
    "profile.namePlaceholder": "Tinye aha gị n'uju",
    "profile.emailPlaceholder": "Tinye email gị",
    "profile.phonePlaceholder": "Tinye nọmba ekwentị gị",
    "profile.passwordPlaceholder": "Tinye okwuntughe ọhụrụ (opekata mpe mkpụrụedemede 6)",
    "profile.confirmPasswordPlaceholder": "Kwado okwuntughe ọhụrụ",
    "profile.loadFailed": "A kụghị ibugo profaịlụ",
    "profile.updated": "Emelitere profaịlụ nke ọma!",
    "profile.passwordsNoMatch": "Okwuntughe adabaghị",
    "profile.passwordTooShort": "Okwuntughe ga-abụ opekata mpe mkpụrụedemede 6",
    "profile.passwordUpdated": "Emelitere okwuntughe nke ọma!",
    "profile.passwordUpdateFailed": "A kụghị imelite okwuntughe",
    // Index / Landing
    "index.welcome": "Nnọọ na",
    "index.subtitle": "Ngwọta nlekọta ngwa ahịa na ahịa zuru oke nke emere maka ndị nwe ụlọ ahịa nwere obere azụmahịa. Ọ dị mfe, dị ike, ma na-arụ ọrụ offline.",
    "index.getStarted": "Malite",
    "index.featuresTitle": "Ihe niile ị chọrọ iji jikwaa ụlọ ahịa gị",
    "index.featuresSubtitle": "Emere ya maka ịdị mfe, na maka uto",
    "index.feature1Title": "Nlekọta Ahịa n'Oge",
    "index.feature1Desc": "Na-eleba anya na ahịa gị ka ha na-eme site na mmelite ozugbo",
    "index.feature2Title": "Njikwa Ngwa Ahịa Dị Elu",
    "index.feature2Desc": "Na-eleba anya na ngwa ahịa gị site na dọ aka na ntị mgbe ha na-agwụ agwụ",
    "index.feature3Title": "Nchebe na Ntụkwasị Obi",
    "index.feature3Desc": "A na-echekwa data gị site na nchebe zuru oke na nchekwa kwa ụbọchị",
    "index.feature4Title": "Na-arụ ọrụ Offline",
    "index.feature4Desc": "Dee ahịa gị ọbụna mgbe ị nọghị n'ịntanetị. Ọ na-emekọrịta ozugbo ị banyere n'ịntanetị",
    "index.ctaTitle": "Ị dịla njikere ịgbanwe azụmahịa gị?",
    "index.ctaSubtitle": "Soro ọtụtụ ndị nwe ụlọ ahịa tụkwasịrị ShopCount obi iji jikwaa ngwa ahịa na ahịa ha",
    "index.startTrial": "Malite Nlele n'Efere",
    // Install
    "install.title": "Wụnye ShopCount",
    "install.subtitle": "Nweta ahụmịhe ngwa mkpanaaka",
    "install.installedTitle": "Awụnyela Ngwa!",
    "install.installedDesc": "Awụnyela ShopCount na ngwaọrụ gị ugbu a. Ị nwere ike ịbanye na ya site na ihuenyo mbụ gị.",
    "install.whyTitle": "Gịnị kpatara eji awụnye ShopCount?",
    "install.feature1": "Na-arụ ọrụ offline - Dee ahịa ọbụna mgbe ị nọghị n'ịntanetị",
    "install.feature2": "Ịbanye ngwa ngwa site na ihuenyo mbụ",
    "install.feature3": "Ibugo ngwa ngwa na arụmọrụ mara mma",
    "install.feature4": "Ahụmịhe ngwa zuru oke",
    "install.button": "Wụnye Ngwa",
    "install.howTitle": "Iji wụnye ShopCount na ngwaọrụ gị:",
    "install.howIos": "Kpatụ bọtịnụ Share, tinyezie \"Add to Home Screen\"",
    "install.howAndroid": "Kpatụ menu (⋮), tinyezie \"Add to Home Screen\" ma ọ bụ \"Install App\"",
    "install.offlineTitle": "Ọrụ Ndị Dị n'Offline:",
    "install.offline1": "Dekọọ ahịa",
    "install.offline2": "Lee ngwa ahịa",
    "install.offline3": "Lelee ịdọ aka na ntị maka ngwa na-agwụ agwụ",
    "install.offline4": "Lelee ihe omume n'oge na-adịbeghị anya",
    "install.syncNote": "Omume niile ị mere n'offline ga-emekọrịta ozugbo ị banyere n'ịntanetị.",
    // Auth
    "auth.tagline": "Nlekọta Ngwa Ahịa & Ahịa maka Obere Azụmahịa",
    "auth.loginTab": "Banye",
    "auth.signupTab": "Debanye aha",
    "auth.resetPasswordTitle": "Tọgharịa Okwuntughe",
    "auth.emailLabel": "Email",
    "auth.emailPlaceholder": "Tinye email gị",
    "auth.passwordLabel": "Okwuntughe",
    "auth.passwordPlaceholder": "Tinye okwuntughe gị",
    "auth.forgotPassword": "Chefuru okwuntughe?",
    "auth.loginButton": "Banye",
    "auth.loggingIn": "Na-abanye...",
    "auth.loginSuccess": "Ị banyere nke ọma!",
    "auth.signupNameLabel": "Aha n'uju",
    "auth.signupNamePlaceholder": "Tinye aha gị n'uju",
    "auth.signupPhoneLabel": "Nọmba Ekwentị (Nhọrọ)",
    "auth.signupPhonePlaceholder": "Tinye nọmba ekwentị gị",
    "auth.signupPasswordLabel": "Okwuntughe",
    "auth.signupPasswordPlaceholder": "Mepụta okwuntughe (opekata mpe mkpụrụedemede 6)",
    "auth.signupButton": "Mepụta Akaụntụ",
    "auth.signingUp": "Na-emepụta akaụntụ...",
    "auth.signupSuccess": "Emepụtara akaụntụ nke ọma!",
    "auth.resetLinkButton": "Zipu Link Ntọgharị",
    "auth.sending": "Na-ezipu...",
    "auth.resetLinkSent": "Ezipụla email ntọgharị okwuntughe! Lelee igbe mbata gị.",
    "auth.backToLogin": "Laghachi na Mbanye",
    "auth.termsNote": "Site n'ịga n'ihu, ị kwenyere na Usoro Ọrụ anyị na amụma nzuzo anyị",
    // NotFound
    "notfound.title": "404",
    "notfound.subtitle": "Ewoo! Agtaghị ibe a",
    "notfound.returnHome": "Laghachi n'Ihuenyo Mbụ",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Nnọọ! Nke a bụ nchịkọta azụmahịa gị",
    "dashboard.todaySales": "Ahịa Taa",
    "dashboard.totalStock": "Ngwa Niile",
    "dashboard.lowStock": "Ngwa na-efu efu",
    "dashboard.totalProfit": "Uru Niile",
    "dashboard.productsSold": "ngwa e rere",
    "dashboard.totalInventory": "Ngụkọta uru ngwa ahịa",
    "dashboard.needAttention": "ndị chọrọ nlebara anya",
    "dashboard.allGood": "Ngwa niile dị mma",
    "dashboard.units": "Nkeji",
    "dashboard.recentActivity": "Ihe Omume N'oge Na-adịbeghị Anya",
    "dashboard.noActivity": "Enweghị ihe omume ọ bụla n'oge na-adịbeghị anya",
    "dashboard.quickActions": "Omume Ngwa Ngwa",
    "dashboard.stockAdded": "Etinyere ngwa",
    "dashboard.saleRecorded": "E dekọrọ ahịa",
    "dashboard.stockAdjusted": "E doziri ngwa",
    "dashboard.viewAll": "Lee niile",
    // Inventory
    "inventory.title": "Njikwa Ngwa Ahịa",
    "inventory.subtitle": "Jikwaa ngwa ahịa gị na ọkwa ha",
    "inventory.addProduct": "Tinye Ngwa",
    "inventory.editProduct": "Dezie Ngwa",
    "inventory.updateProduct": "Melite Ngwa",
    "inventory.productName": "Aha Ngwa",
    "inventory.category": "Udi",
    "inventory.categoryOptional": "Udi (Nhọrọ)",
    "inventory.costPrice": "Ọnụ Ego Zụrụ",
    "inventory.sellingPrice": "Ọnụ Ahịa",
    "inventory.stock": "Ngwa Dị",
    "inventory.initialStock": "Ngwa Mbụ",
    "inventory.threshold": "Ịdọ Aka na Ntị Maka Ngwa",
    "inventory.searchPlaceholder": "Chọọ ngwa ahịa...",
    "inventory.allCategories": "Ụdị Niile",
    "inventory.noProducts": "Enweghị ngwa ahịa tupu",
    "inventory.noProductsHint": "Malite site n'itinye ngwa ahịa mbụ gị",
    "inventory.addProductFirst": "Tinye Ngwa Mbụ Gị",
    "inventory.noProductsFound": "Achọpụtaghị ngwa ahịa ọ bụla",
    "inventory.adjustSearch": "Gbalịa ịgbanwe ihe ị na-achọ",
    "inventory.inStock": "dị",
    "inventory.profitUnit": "Uru/Nkeji",
    "inventory.addStock": "Tinye Ngwa Dị",
    "inventory.stockQty": "Ọnụ Ọgụgụ A Ga-etinye",
    "inventory.enterQty": "Tinye ọnụ ọgụgụ",
    "inventory.currentStockHint": "Ngwa dị ugbu a: {count} nkeji",
    "inventory.deleteConfirm": "Hichapụ Ngwa?",
    "inventory.deleteDescription": "Ị doro anya na ị chọrọ ihichapụ \"{name}\"? Enweghị ike ịmegharị nke a.",
    "inventory.manageInventory": "Jikwaa Ngwa Ahịa",
    "inventory.stockLabel": "Ngwa",
    // Sales
    "sales.title": "Dee Ahịa",
    "sales.subtitle": "Dekọọ ahịa ngwa ngwa na n'ụzọ dị mfe",
    "sales.selectProduct": "Họrọ Ngwa",
    "sales.selectProductPlaceholder": "Chọọ ngwa...",
    "sales.unitPrice": "Ọnụ Ego Otu",
    "sales.profitPerUnit": "Uru/Nkeji",
    "sales.availableStock": "Ngwa Dị",
    "sales.quantity": "Ọnụ Ọgụgụ",
    "sales.quantityPlaceholder": "Tinye ọnụ ọgụgụ",
    "sales.totalAmount": "Ego Niile",
    "sales.totalProfitLabel": "Uru Niile",
    "sales.recording": "Na-edekọ...",
    "sales.recordSale": "Dee Ahịa",
    "sales.downloadReceipt": "Budata Akwụkwọ Ahịa",
    "sales.recordedAndSynced": "E dekọrọ ma mekọrịta ahịa!",
    "sales.savedOffline": "Echekwara na ekwentị (ga-emekọrịta ma emechaa)",
    "sales.loadFailed": "A kụghị ibugo ngwa ahịa",
    "sales.enterValidQuantity": "Biko họrọ ngwa ma tinye ọnụ ọgụgụ dị mma",
    "sales.insufficientStock": "Ngwa dị ebe a ezughị",
    "sales.failed": "A kụghị idekọ ahịa",
    "sales.receiptDownloaded": "E budatara akwụkwọ ahịa!",
    "sales.allSynced": "Emekọrịta ihe niile",
    "sales.pendingSyncs": "Ahịa {count} na-eche nmekọrịta",
    // Reports
    "reports.title": "Akụkọ na Nyocha",
    "reports.subtitle": "Soro ọrụ ahịa gị",
    "reports.daily": "Ụbọchị",
    "reports.weekly": "Izu",
    "reports.monthly": "Ọnwa",
    "reports.revenue": "Ego Nnata",
    "reports.profit": "Uru",
    "reports.salesTrend": "Usoro Ahịa",
    "reports.topProducts": "Ngwa Ahịa Kasị Mma",
    "reports.noData": "Enweghị data ahịa",
    "reports.unitsSold": "e rere",
    "reports.loading": "Na-ebugo...",
    "reports.failed": "A kụghị akụkọ",
    // Reconciliation
    "reconciliation.title": "Nhazi Ego",
    "reconciliation.subtitle": "Tụnyere ego a tụrụ anya na nke e natara",
    "reconciliation.new": "Nhazi Ọhụrụ",
    "reconciliation.date": "Ụbọchị",
    "reconciliation.expected": "Ego A Tụrụ Anya",
    "reconciliation.expectedHint": "Dabere na ahịa maka",
    "reconciliation.received": "Ego E Natara",
    "reconciliation.receivedPlaceholder": "Tinye ego e natara",
    "reconciliation.discrepancyDetected": "Achọpụtara nghọta",
    "reconciliation.perfectMatch": "Zuru oke!",
    "reconciliation.short": "O nweghị",
    "reconciliation.over": "O karịrị",
    "reconciliation.notes": "Ndetu",
    "reconciliation.notesPlaceholder": "Tinye ndetu maka nhazi a...",
    "reconciliation.submit": "Nyefee Nhazi",
    "reconciliation.history": "Ndekọ N'oge Na-adị",
    "reconciliation.noRecords": "Enwebeghị ndekọ",
    "reconciliation.approved": "Ekwenyere",
    "reconciliation.disputed": "A rụrụ ụka",
    "reconciliation.saving": "Na-echekwa nhazi...",
    "reconciliation.saved": "Echekwara ndekọ nhazi!",
    "reconciliation.failed": "A kụghị nchekwa nhazi",
    "reconciliation.loadFailed": "A kụghị ibugo ndekọ nhazi",
    "reconciliation.enterAmount": "Biko tinye ego e natara",
    "reconciliation.expectedLabel": "A Tụrụ Anya",
    "reconciliation.receivedLabel": "A Natara",
    "reconciliation.statusApproved": "Ekwenyere",
    "reconciliation.statusDisputed": "A rụrụ ụka",
    "reconciliation.isPartial": "Nke a bụ nzukọ n'akụkụ (dowe ahịa fọdụrụ maka emesịa)",
    // Audit Log
    "audit.title": "Akwụkwọ Ọrụ",
    "audit.subtitle": "Soro mgbanwe ngwa niile",
    "audit.action": "Ọrụ",
    "audit.product": "Ngwa",
    "audit.quantity": "Mgbanwe Ọnụ Ọgụgụ",
    "audit.date": "Ụbọchị",
    "audit.noLogs": "Enweghị ndekọ ọrụ",
    "audit.loadFailed": "A kụghị ibugo ndekọ ọrụ",
    "audit.previousStock": "Ngwa Mbụ",
    "audit.newStock": "Ngwa Ọhụrụ",
    "audit.actionSale": "Ahịa",
    "audit.actionRestock": "Tinye Ngwa",
    "audit.actionAdjustment": "Ndozi",
    // Team
    "team.title": "Njikwa Ndị Otu",
    "team.subtitle": "Jikwaa ndị na-ere ahịa gị",
    "team.addRep": "Tinye Onye Ahịa",
    "team.createAccount": "Mepụta Akaụntụ",
    "team.noReps": "Enwebeghị ndị na-ere ahịa",
    "team.noRepsHint": "Tinye onye na-ere ahịa mbụ iji malite",
    "team.dateAdded": "Ụbọchị Etinyere",
    "team.repAdded": "Etinyere onye na-ere ahịa!",
    "team.repRemoved": "Ewepụrụ onye na-ere ahịa",
    "team.passwordNote": "A ga-emepụta okwuntughe na-akpaghị aka. Ị ga-ahụ nzere mgbe emechara.",
    "team.credentialsTitle": "Nzere Onye Ahịa",
    "team.credentialsWarning": "Chekwaa nzere ndị a ugbu a! Agaghị enwe ike ịnwetaghachi okwuntughe.",
    "team.done": "Emechara",
    "team.addFailed": "A kụghị n'atụnye onye ahịa",
    "team.removeConfirm": "Wepu {name} n'otu gị?",
    "team.removeFailed": "A kụghị iwepụ onye otu",
    "team.loadFailed": "A kụghị ibugo ndị otu",
    "team.fillFields": "Biko dejupụta ebe niile",
    // Feedback
    "feedback.button": "Nzaghachi",
  },
  yo: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.inventory": "Àkópọ̀ Ọjà",
    "nav.sales": "Kọ Títà",
    "nav.reports": "Ìròyìn",
    "nav.reconciliation": "Ìṣàtúnṣe",
    "nav.audit": "Àkọsílẹ̀ Iṣẹ́",
    "nav.team": "Ẹgbẹ́",
    "nav.profile": "Profaili",
    "nav.install": "Fi App sí",
    "nav.signout": "Jáde",
    "nav.navigation": "Ìrìnàjò",
    // Common
    "common.save": "Fipamọ́ Àyípadà",
    "common.saving": "Ń fipamọ́...",
    "common.loading": "Ń gbé...",
    "common.search": "Wá",
    "common.filter": "Yàn",
    "common.add": "Fi kún",
    "common.edit": "Ṣàtúnṣe",
    "common.delete": "Pa rẹ́",
    "common.cancel": "Fagilee",
    "common.confirm": "Jẹ́rìí",
    "common.actions": "Ìṣe",
    "common.system": "Sistemù",
    "common.unknownProduct": "Ọjà tí a kò mọ̀",
    "common.copied": "A ti ṣàdàkọ rẹ̀!",
    "common.staff": "Òṣìṣẹ́",
    "common.unknown": "Kò mọ̀",
    // Profile
    "profile.title": "Ètò Profaili",
    "profile.subtitle": "Ṣàkóso àlàyé àkọọ́lẹ̀ rẹ",
    "profile.personal": "Àlàyé Ti ara ẹni",
    "profile.name": "Orúkọ Kíkún",
    "profile.email": "Ímeèlì",
    "profile.phone": "Nọ́mbà Fóònù",
    "profile.password": "Yí Ọ̀rọ̀ Aṣínà Padà",
    "profile.newPassword": "Ọ̀rọ̀ Aṣínà Tuntun",
    "profile.confirmPassword": "Jẹ́rìí Ọ̀rọ̀ Aṣínà Tuntun",
    "profile.updatePassword": "Ṣe àtúnṣe Ọ̀rọ̀ Aṣínà",
    "profile.preferences": "Àṣàyàn",
    "profile.currency": "Owó",
    "profile.language": "Èdè",
    "profile.selectCurrency": "Yàn owó",
    "profile.selectLanguage": "Yàn èdè",
    "profile.namePlaceholder": "Fi orúkọ rẹ kíkún síbẹ̀",
    "profile.emailPlaceholder": "Fi ímeèlì rẹ síbẹ̀",
    "profile.phonePlaceholder": "Fi nọ́mbà fóònù rẹ síbẹ̀",
    "profile.passwordPlaceholder": "Fi ọ̀rọ̀ aṣínà tuntun síbẹ̀ (aìkéré tán lẹ́tà 6)",
    "profile.confirmPasswordPlaceholder": "Jẹ́rìí ọ̀rọ̀ aṣínà tuntun",
    "profile.loadFailed": "Profaili kò gbé",
    "profile.updated": "A ti ṣe àtúnṣe profaili rẹ yọ̀fẹ́!",
    "profile.passwordsNoMatch": "Àwọn ọ̀rọ̀ aṣínà kò dọ́gba",
    "profile.passwordTooShort": "Ọ̀rọ̀ aṣínà gbọ́dọ̀ kéré tán lẹ́tà mẹ́fà",
    "profile.passwordUpdated": "A ti ṣe àtúnṣe ọ̀rọ̀ aṣínà rẹ yọ̀fẹ́!",
    "profile.passwordUpdateFailed": "Àtúnṣe ọ̀rọ̀ aṣínà kùnà",
    // Index / Landing
    "index.welcome": "Ẹ kú àbọ̀ sí",
    "index.subtitle": "Ètò tọpinpin àkópọ̀ ọjà àti títà tí a ṣe pàtàkì fún àwọn oníṣòwò kékeré. Ó rọrùn, ó lágbára, ó sì ń ṣiṣẹ́ láìsí íńtánẹ́ẹ̀tì.",
    "index.getStarted": "Bẹ̀rẹ̀",
    "index.featuresTitle": "Gbogbo nǹkan tí o nílò láti ṣàkóso ìṣòwò rẹ",
    "index.featuresSubtitle": "A ṣe é fún ìrọ̀rùn àti ìdàgbàsókè",
    "index.feature1Title": "Tọpinpin Títà ní Ìṣẹ́jú-kọ̀kan",
    "index.feature1Desc": "Mójútó títà rẹ bí ó ṣe ń ṣẹlẹ̀ pẹ̀lú ìṣèsí tuntun lẹ́sẹ̀kẹsẹ̀",
    "index.feature2Title": "Ìṣàkóso Àkópọ̀ Ọjà Tí Ó Gbọ́n",
    "index.feature2Desc": "Tọpinpin iye ọjà rẹ pẹ̀lú ìkìlọ̀ fún ọjà tó ń dín kù fúnra rẹ̀",
    "index.feature3Title": "Àìléwu & Gbẹ́kẹ̀lé",
    "index.feature3Desc": "Àlàyé rẹ wà nípamọ́ pẹ̀lú ààbò tó múnádóko àti ìpamọ́ ojúmọ́",
    "index.feature4Title": "Ń ṣiṣẹ́ láìsí Íńtánẹ́ẹ̀tì",
    "index.feature4Desc": "Kọ títà rẹ sílẹ̀ lásìkò tí kò bá sí íńtánẹ́ẹ̀tì. Ó ń mú un dọ́gba padà bí iṣẹ́ bá bẹ̀rẹ̀",
    "index.ctaTitle": "Ṣé o ti ṣe tán láti yí ìṣòwò rẹ padà?",
    "index.ctaSubtitle": "Darapọ̀ mọ́ àwọn oníṣòwò ọgọ́rọ̀ọ̀rún tí wọ́n gbẹ́kẹ̀lé ShopCount fún ìṣàkóso wọn",
    "index.startTrial": "Bẹ̀rẹ̀ Ìdánwò Ọ̀fẹ́",
    // Install
    "install.title": "Fi ShopCount sí",
    "install.subtitle": "Gba ìrírí ìṣàfilọ́lẹ̀ fóònù",
    "install.installedTitle": "A ti fi App sí!",
    "install.installedDesc": "A ti fi ShopCount sí orí fóònù rẹ báyìí. O le rí i ní ojú-ìbẹ̀rẹ̀ fóònù rẹ.",
    "install.whyTitle": "Èéṣe tí o fi gbọ́dọ̀ fi ShopCount sí?",
    "install.feature1": "Ń ṣiṣẹ́ láìsí íńtánẹ́ẹ̀tì - Kọ títà sílẹ̀ lásìkò tí kò bá sí íńtánẹ́ẹ̀tì",
    "install.feature2": "Wọle kánkán láti ojú-ìbẹ̀rẹ̀",
    "install.feature3": "Ó ń gbé kánkán pẹ̀lú àmúṣe tó dára",
    "install.feature4": "Ìrírí ìṣàfilọ́lẹ̀ ní kíkún",
    "install.button": "Fi App sí",
    "install.howTitle": "Láti fi ShopCount sí orí fóònù rẹ:",
    "install.howIos": "Tẹ bọ́tìnì Share, lẹ́yìn náà \"Add to Home Screen\"",
    "install.howAndroid": "Tẹ menu (⋮), lẹ́yìn náà \"Add to Home Screen\" tàbí \"Install App\"",
    "install.offlineTitle": "Àwọn iṣẹ́ tó wà lásìkò tí kò sí íńtánẹ́ẹ̀tì:",
    "install.offline1": "Kọ àkọsílẹ̀ títà",
    "install.offline2": "Wo àkópọ̀ ọjà",
    "install.offline3": "Ṣàyẹ̀wò ìkìlọ̀ ọjà tó ń dín kù",
    "install.offline4": "Wo àwọn iṣẹ́ àìpẹ́",
    "install.syncNote": "Gbogbo iṣẹ́ tí o ṣe lásìkò tí kò sí íńtánẹ́ẹ̀tì yóò mú ara wọn dọ́gba lójú ẹsẹ̀ tí íńtánẹ́ẹ̀tì bá padà dé.",
    // Auth
    "auth.tagline": "Tọpinpin Ọjà & Títà fún Àwọn Ìṣòwò Kékeré",
    "auth.loginTab": "Woṣẹ́",
    "auth.signupTab": "Forúkọsílẹ̀",
    "auth.resetPasswordTitle": "Padà Ṣe Ọ̀rọ̀ Aṣínà",
    "auth.emailLabel": "Ímeèlì",
    "auth.emailPlaceholder": "Fi ímeèlì rẹ síbẹ̀",
    "auth.passwordLabel": "Ọ̀rọ̀ Aṣínà",
    "auth.passwordPlaceholder": "Fi ọ̀rọ̀ aṣínà rẹ síbẹ̀",
    "auth.forgotPassword": "O gbàgbé ọ̀rọ̀ aṣínà?",
    "auth.loginButton": "Woṣẹ́",
    "auth.loggingIn": "Ń gbé iṣẹ́ wọlé...",
    "auth.loginSuccess": "O ti woṣẹ́ yọ̀fẹ́!",
    "auth.signupNameLabel": "Orúkọ Kíkún",
    "auth.signupNamePlaceholder": "Fi orúkọ rẹ kíkún síbẹ̀",
    "auth.signupPhoneLabel": "Nọ́mbà Fóònù (Kò pọn dandan)",
    "auth.signupPhonePlaceholder": "Fi nọ́mbà fóònù rẹ síbẹ̀",
    "auth.signupPasswordLabel": "Ọ̀rọ̀ Aṣínà",
    "auth.signupPasswordPlaceholder": "Ṣẹ̀dá ọ̀rọ̀ aṣínà kan (aìkéré tán lẹ́tà 6)",
    "auth.signupButton": "Ṣẹ̀dá Àkọọ́lẹ̀",
    "auth.signingUp": "Ń ṣẹ̀dá àkọọ́lẹ̀ rẹ...",
    "auth.signupSuccess": "A ti ṣẹ̀dá àkọọ́lẹ̀ rẹ yọ̀fẹ́!",
    "auth.resetLinkButton": "Fi Ìjápọ̀ Padà Ṣe Ránṣẹ́",
    "auth.sending": "Ń ránṣẹ́...",
    "auth.resetLinkSent": "A ti fi ímeèlì padà ṣe ọ̀rọ̀ aṣínà ránṣẹ́! Yẹ apótí ímeèlì rẹ wò.",
    "auth.backToLogin": "Padà sí Woṣẹ́",
    "auth.termsNote": "Nípa títẹ̀síwájú, o gbà sí Àwọn Ìlànà Iṣẹ́ wa ati Ètò Ìpamọ́ wa",
    // NotFound
    "notfound.title": "404",
    "notfound.subtitle": "Óò! A kò rí ojú-ìwé yìí",
    "notfound.returnHome": "Padà sí Ojú-ìbẹ̀rẹ̀",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Ẹ kú àbọ̀! Èyí ni àpapọ̀ iṣẹ́ rẹ",
    "dashboard.todaySales": "Títà Òní",
    "dashboard.totalStock": "Àpapọ̀ Ọjà",
    "dashboard.lowStock": "Ọjà tí ó kéré",
    "dashboard.totalProfit": "Àpapọ̀ Èrè",
    "dashboard.productsSold": "ọjà tí a tà",
    "dashboard.totalInventory": "Iye àpapọ̀ ọjà",
    "dashboard.needAttention": "nílò àbójútó",
    "dashboard.allGood": "Gbogbo ọjà wà ní ìwọ̀n tó dára",
    "dashboard.units": "Àwọn Ẹyọ",
    "dashboard.recentActivity": "Àwọn Iṣẹ́ Àìpẹ́",
    "dashboard.noActivity": "Kò sí iṣẹ́ kankan láìpẹ́ yìí",
    "dashboard.quickActions": "Àwọn Ìṣe Kánkán",
    "dashboard.stockAdded": "A fi ọjà kún",
    "dashboard.saleRecorded": "A kọ títà",
    "dashboard.stockAdjusted": "A tún ọjà ṣe",
    "dashboard.viewAll": "Wo Gbogbo",
    // Inventory
    "inventory.title": "Ìṣàkóso Àkópọ̀ Ọjà",
    "inventory.subtitle": "Ṣàkóso àwọn ọjà rẹ àti iye wọn",
    "inventory.addProduct": "Fi Ọjà Kún",
    "inventory.editProduct": "Ṣàtúnṣe Ọjà",
    "inventory.updateProduct": "Ṣe Àtúnṣe Ọjà",
    "inventory.productName": "Orúkọ Ọjà",
    "inventory.category": "Irú",
    "inventory.categoryOptional": "Irú (Àṣàyàn)",
    "inventory.costPrice": "Iye Owó Rírà",
    "inventory.sellingPrice": "Iye Owó Títà",
    "inventory.stock": "Ọjà Tó Wà",
    "inventory.initialStock": "Ọjà Àkọ́kọ́",
    "inventory.threshold": "Ìkìlọ̀ Ọjà Kékeré",
    "inventory.searchPlaceholder": "Wá ọjà...",
    "inventory.allCategories": "Gbogbo Irú Ọjà",
    "inventory.noProducts": "Kò sí ọjà kankan báyìí",
    "inventory.noProductsHint": "Bẹ̀rẹ̀ nípa fífí ọjà rẹ àkọ́kọ́ kún",
    "inventory.addProductFirst": "Fi Ọjà Rẹ Àkọ́kọ́ Kún",
    "inventory.noProductsFound": "A kò rí ọjà kankan",
    "inventory.adjustSearch": "Gbìyànjú láti yí ohun tí o ń wá padà",
    "inventory.inStock": "wà lọ́wọ́",
    "inventory.profitUnit": "Èrè/Ẹyọ",
    "inventory.addStock": "Fi Ọjà Kún",
    "inventory.stockQty": "Iye tí o fẹ́ fi kún",
    "inventory.enterQty": "Fi iye rẹ̀ síbẹ̀",
    "inventory.currentStockHint": "Iye tó wà lọ́wọ́: {count} ẹyọ",
    "inventory.deleteConfirm": "Pa Ọjà Rẹ́?",
    "inventory.deleteDescription": "Ṣé o dá mọ̀ pé o fẹ́ pa \"{name}\" rẹ́? O kò ní lè rí i mọ́.",
    "inventory.manageInventory": "Ṣàkóso Ọjà",
    "inventory.stockLabel": "Ọjà",
    // Sales
    "sales.title": "Kọ Títà",
    "sales.subtitle": "Kọ títà rẹ kánkán àti pẹ̀lú ìrọ̀rùn",
    "sales.selectProduct": "Yàn Ọjà",
    "sales.selectProductPlaceholder": "Wá ọjà...",
    "sales.unitPrice": "Iye Owó Ẹyọ kan",
    "sales.profitPerUnit": "Èrè/Ẹyọ",
    "sales.availableStock": "Ọjà Tó Wà lọ́wọ́",
    "sales.quantity": "Iye",
    "sales.quantityPlaceholder": "Fi iye rẹ̀ síbẹ̀",
    "sales.totalAmount": "Àpapọ̀ Owó",
    "sales.totalProfitLabel": "Àpapọ̀ Èrè",
    "sales.recording": "Ń kọ iṣẹ́...",
    "sales.recordSale": "Kọ Títà",
    "sales.downloadReceipt": "Gba Takàdá Títà",
    "sales.recordedAndSynced": "A ti kọ títà tí a sì ti mú dọ́gba!",
    "sales.savedOffline": "A ti fipamọ́ sórí fóònù (yóò mú dọ́gba bọ̀rọ̀)",
    "sales.loadFailed": "Ọjà kò gbé",
    "sales.enterValidQuantity": "Jọ̀wọ́ yàn ọjà kan kí o sì fi iye tó dọ́gba síbẹ̀",
    "sales.insufficientStock": "Ọjà tó wà lọ́wọ́ kò tó",
    "sales.failed": "Títà kò kọ",
    "sales.receiptDownloaded": "A ti gba takàdá títà!",
    "sales.allSynced": "Gbogbo rẹ̀ ti dọ́gba",
    "sales.pendingSyncs": "Títà {count} ń dúró láti mú dọ́gba",
    // Reports
    "reports.title": "Ìròyìn àti Ìtúpalẹ̀",
    "reports.subtitle": "Tọpinpin àmúṣe títà rẹ",
    "reports.daily": "Ojoojúmọ́",
    "reports.weekly": "Ọ̀sọ̀ọ̀sẹ̀",
    "reports.monthly": "Oṣooṣù",
    "reports.revenue": "Owó Tó Wọlé",
    "reports.profit": "Èrè",
    "reports.salesTrend": "Ìtẹ̀síwájú Títà",
    "reports.topProducts": "Ọjà Tí A Ń Tà Jùlọ",
    "reports.noData": "Kò sí ìròyìn títà",
    "reports.unitsSold": "a tà",
    "reports.loading": "Ń gbé...",
    "reports.failed": "Ìròyìn kò gbé",
    // Reconciliation
    "reconciliation.title": "Ìṣàtúnṣe Owó",
    "reconciliation.subtitle": "Ṣe àfiwé owó tí a ń retí àti èyí tí a gba",
    "reconciliation.new": "Ìṣàtúnṣe Tuntun",
    "reconciliation.date": "Ọjọ́",
    "reconciliation.expected": "Owó Tí A Ń Retí",
    "reconciliation.expectedHint": "Dábere lórí títà fún",
    "reconciliation.received": "Owó Tí A Gba",
    "reconciliation.receivedPlaceholder": "Fi owó tí o gba síbẹ̀",
    "reconciliation.discrepancyDetected": "Ìyàtọ̀ wà",
    "reconciliation.perfectMatch": "Ó múná dọ́gba!",
    "reconciliation.short": "Ó dín",
    "reconciliation.over": "Ó ju",
    "reconciliation.notes": "Àkọsílẹ̀",
    "reconciliation.notesPlaceholder": "Fi àkọsílẹ̀ kún ìṣàtúnṣe yìí...",
    "reconciliation.submit": "Fi Ìṣàtúnṣe Ránṣẹ́",
    "reconciliation.history": "Àkọsílẹ̀ Àìpẹ́",
    "reconciliation.noRecords": "Kò sí àkọsílẹ̀ kankan",
    "reconciliation.approved": "A fọwọ́sí",
    "reconciliation.disputed": "A tako",
    "reconciliation.saving": "Ń fipamọ́ ìṣàtúnṣe...",
    "reconciliation.saved": "A ti fipamọ́ ìṣàtúnṣe!",
    "reconciliation.failed": "Ìṣàtúnṣe kò fipamọ́",
    "reconciliation.loadFailed": "Àkọsílẹ̀ ìṣàtúnṣe kò gbé",
    "reconciliation.enterAmount": "Jọ̀wọ́ fi iye owó tí o gba síbẹ̀",
    "reconciliation.expectedLabel": "Ti A Retí",
    "reconciliation.receivedLabel": "Ti A Gba",
    "reconciliation.statusApproved": "A fọwọ́sí",
    "reconciliation.statusDisputed": "A tako",
    "reconciliation.isPartial": "Èyí jẹ́ ìṣírò ọ̀kan lára apá kan (pa ìyókù títà mọ́ fún ìgbà mìíràn)",
    // Audit Log
    "audit.title": "Àkọsílẹ̀ Iṣẹ́",
    "audit.subtitle": "Tọpinpin gbogbo àyípadà àkópọ̀",
    "audit.action": "Ìṣe",
    "audit.product": "Ọjà",
    "audit.quantity": "Àyípadà Iye",
    "audit.date": "Ọjọ́",
    "audit.noLogs": "Kò sí àkọsílẹ̀ kankan",
    "audit.loadFailed": "Àkọsílẹ̀ kò gbé",
    "audit.previousStock": "Ọjà tẹ́lẹ̀",
    "audit.newStock": "Tuntun Ọjà",
    "audit.actionSale": "Títà",
    "audit.actionRestock": "Fi Kún",
    "audit.actionAdjustment": "Ìṣàtúnṣe",
    // Team
    "team.title": "Ìṣàkóso Ẹgbẹ́",
    "team.subtitle": "Ṣàkóso àwọn olùtajà rẹ",
    "team.addRep": "Fi Olùtajà Kún",
    "team.createAccount": "Ṣẹ̀dá Àkọọ́lẹ̀",
    "team.noReps": "Kò sí olùtajà kankan",
    "team.noRepsHint": "Fi olùtajà àkọ́kọ́ kún láti bẹ̀rẹ̀",
    "team.dateAdded": "Ọjọ́ Tí A Fi Kún",
    "team.repAdded": "A ti fi olùtajà kún!",
    "team.repRemoved": "A ti yọ olùtajà kúrò",
    "team.passwordNote": "Ọ̀rọ̀ aṣínà yóò jẹ́ ṣíṣẹ̀dá fúnra rẹ̀. Ìwọ yóò rí ìpamọ́ lẹ́yìn ìṣẹ̀dá.",
    "team.credentialsTitle": "Ìpamọ́ Olùtajà",
    "team.credentialsWarning": "Fi àwọn ìpamọ́ wọ̀nyí pamọ́ báyìí! Ọ̀rọ̀ aṣínà kò lè jẹ́ gbígba padà.",
    "team.done": "Parí",
    "team.addFailed": "Olùtajà kò kún",
    "team.removeConfirm": "Yọ {name} kúrò nínú ẹgbẹ́ rẹ?",
    "team.removeFailed": "A kò lè yọ ọmọ ẹgbẹ́ kúrò",
    "team.loadFailed": "Àwọn ọmọ ẹgbẹ́ kò gbé",
    "team.fillFields": "Jọ̀wọ́ kọ gbogbo ààyè síbẹ̀",
    // Feedback
    "feedback.button": "Èsì",
  },
};

export function SettingsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [currency, setCurrencyState] = useState<Currency>("NGN");
  const [language, setLanguageState] = useState<Language>("en");

  // Load settings from localStorage on mount
  useEffect(() => {
    const savedCurrency = localStorage.getItem("shopcount_currency") as Currency;
    const savedLanguage = localStorage.getItem("shopcount_language") as Language;

    if (savedCurrency && currencies.some(c => c.code === savedCurrency)) {
      setCurrencyState(savedCurrency);
    }
    if (savedLanguage && languages.some(l => l.code === savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setCurrency = (newCurrency: Currency) => {
    setCurrencyState(newCurrency);
    localStorage.setItem("shopcount_currency", newCurrency);
  };

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem("shopcount_language", newLanguage);
  };

  const getCurrencyInfo = (): CurrencyInfo => {
    return currencies.find(c => c.code === currency) || currencies[0];
  };

  const formatCurrency = (amount: number): string => {
    const info = getCurrencyInfo();
    return `${info.symbol}${amount.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <SettingsContext.Provider
      value={{
        currency,
        setCurrency,
        language,
        setLanguage,
        formatCurrency,
        t,
        getCurrencyInfo,
      }}
    >
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error("useSettings must be used within a SettingsProvider");
  }
  return context;
}
